# Zsh plugin for Flutter command shortcuts

alias f="flutter"
alias fc="flutter clean"
alias fpg="flutter pub get"
alias fpu="flutter pub upgrade"
alias fr="flutter run"
alias fbapk="flutter build apk"
alias fbab="flutter build appbundle"
alias fd="flutter doctor"
alias ft="flutter test"
alias fan="flutter analyze"
alias fdv="flutter devices"
alias fem="flutter emulators"
alias fio="open ios/Runner.xcworkspace"
alias fup="flutter upgrade"
alias fpl="flutter pub outdated"
